dist: trusty
language: cpp
compiler:
- gcc
- clang

os:
- linux
- osx

osx_image: xcode11

addons:
  apt:
    packages:
    - doxygen
    - graphviz

env:
  global:
  - PATH=$HOME/_cmake/bin:$HOME/miniconda/bin:$PATH
  - MACOSX_DEPLOYMENT_TARGET=10.7
  - MAKEFLAGS="-j2 ${MAKEFLAGS}"

  jobs:
  - python=3.6 CONDA_PY=36
  - python=3.7 CONDA_PY=37

jobs:
  exclude:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc

cache:
  ccache: true

before_install:
- tools/ci/travis/setup_travis.sh
- tools/ci/travis/install_miniconda.sh

install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export BUILD_TYPE="RelWithDebInfo"; else export BUILD_TYPE="Release"; fi

script:
- conda clean --all -y
- conda-build --version
- conda install conda-verify
- conda build -c defaults -c conda-forge tools/conda-recipe --python=$CONDA_PY

after_success:
- tools/ci/travis/upload_conda_package.sh
- tools/ci/travis/make_docs.sh

notifications:
  email: false
